[package]
name = "esx_view"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
esx_lib = { path = "../esx_lib" }
eframe = "0.26"
egui_extras = "0.26"
rfd = "0.14"

